### ISSUE TITLE
renderToStream bootstrapScripts doesn't allow router's `lazy` to work

### ISSUE THREAD

**Issue by Coachonko** [atellmer/dark#43]
`renderToStream`'s `bootstrapScripts` does not mark scripts with the `type="module"` attribute. 
In the event that the browser bundle is loaded on the browser via this way, loading routes using the `lazy` function will not work, browsers will throw error `Uncaught SyntaxError: Cannot use import statement outside a module (at index.js:1:1)`

Suggested change: add `bootstrapModules` property to `RenderToStreamOptions` that accepts an array of string just like `bootstrapScripts` except the resulting output would be `<script type="module" src="${script}" defer></script>` instead of just `<script src="${script}" defer></script>`

Example of the issue is demonstrated [here](https://github.com/Coachonko/coachonko.com/tree/a1f4355a75310f3a114ac5b76d0484daf0bac6dd)

**Comment by atellmer** [comment]
Ok, I will watch it soon. I need a little time to dive into the problem.
However, it's also worth noting that I wouldn't recommend using document as the application's hydration point, because any browser extension will break everything due to not being represented in the Fiber tree.

**Comment by Coachonko** [comment]
Is there a use for `bootstrapScripts` when not hydrating the whole document? One could manually add the <script> tags in the document head if hydration is only performed in one body element.

**Comment by atellmer** [comment]
In general, `bootstrapScripts` is needed in order to automatically add scripts, the paths to which may be unknown in advance and can be taken from the data of a builder, such as webpack. For example, not `build.js`, but `build-abcd123.js`.
But you can always manually write all the scripts into the `Page` body and not use the `bootstrapScripts` option. It only slightly simplifies what can be done anyway.

**Comment by atellmer** [comment]
I managed to get the example project to the point where I get an error loading the js file. It seems to me that Bun in this configuration does not correctly resolve paths to files and I receive a request to root `/` instead of `/public/` and the server returns me html again instead of js code. As a result, hydration fails with an error 

![1](https://github.com/atellmer/dark/assets/16635118/72428314-2df2-4d00-a93a-58e9fb5ea8a7)
![2](https://github.com/atellmer/dark/assets/16635118/9e799557-9a3b-4f9e-9c31-d5646419412a)
![3](https://github.com/atellmer/dark/assets/16635118/ef2cd07c-62e1-4d44-b003-095e5edea53a)

**Comment by atellmer** [comment]
If you manually remove the extra `../`, then the hydration is successful.
Also an important points: 
1. Page 
```tsx
import { h, component } from '@dark-engine/core'

const Page = component(({ slot }) => {
  return (
    <html>
      <head>
        <meta charset='utf-8' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <base href='/' />
        <title>stream</title>
      </head>
      <body>
        <div id="root">{slot}</div>
        <script type='module' src='/public/index.js'></script>
      </body>
    </html>
  )
})

export default Page
```
 2. Pass `slot` not as a prop, but as a nested object in Navigation
```tsx
import { h, component } from '@dark-engine/core'
import { Router } from '@dark-engine/web-router'

import { routes } from '../routes/routes'
import Navigation from './Navigation'

const App = component(({ url }) => {
  return (
    <Router routes={routes} url={url}>{slot => <Navigation>{slot}</Navigation>}</Router>
  )
})

export default App
```

**Comment by atellmer** [comment]
The problem with paths can be solved by moving `index.js` inside the `pages/` directory, or by somehow setting up Bun

![1](https://github.com/atellmer/dark/assets/16635118/4a938419-2bfe-48a4-84c5-60b420581529)

**Comment by Coachonko** [comment]
Thank you for reporting this path issue, it was hidden by my incorrect usage of the slot property. This is interesting

**Comment by atellmer** [comment]
> I thought that bootstrapScripts would be useful when the entire document is handled by Dark, because then string interpolation in the <head> is not as easy

What do you mean? Can you give an example code where it will not be easy, so that I can better understand your point?
