### ISSUE TITLE
SynthethicEvent currentTarget is undefined

### ISSUE THREAD

**Issue by Coachonko** [atellmer/dark#81]
Dark's SynthethicEvent doesn't seem to have a currentTarget property. Is this a design choice?

**Comment by atellmer** [comment]
As far as I remember, this is due to the implementation of event delegation to a `document`. In this case, `currentTarget` cannot be tracked there. In a synthetic event there is a `sourceEvent` and there the `currentTarget` is always `document`. Therefore, this limitation is caused by the performance struggle of `addEventListener` (this is a heavy operation).
