### ISSUE TITLE
input value not being respected

### ISSUE THREAD

**Issue by Coachonko** [atellmer/dark#82]
In text inputs, the `value` prop doesn't seem to be respected. 
The input HTML attribute value matches the variable in the component state, however the rendered value can differ.
It is a problem particularly when validating user input: invalid values are caught and corrected at the component state level, but displayed value does not match the component state.
This becomes even more of a problem when attempting to utilize `event.target.selectionStart` when the displayed value contains more characters than the state variable
[This is a minimal repro](https://stackblitz.com/edit/darkapp-ccz57rk-1zhv6b?file=index.tsx) although this repro is not particularly refined. I am working on a much larger component at the moment to handle currency input, this behavior blocks me.

**Comment by atellmer** [comment]
Thanks for the example code. The problem is that setTextInputValue does not cause a new render of the component, because the value has not changed (zero remains zero when entering letters), but the browser substitutes the entered text through the internal input state. In this case, you need to additionally synchronize the value of input.

```tsx
  const handleInput = event => {
    const regex = /\D/g;
    const newValue = event.target.value;
    const sanitizedValue = newValue.replace(regex, '');

    setTextInputValue(sanitizedValue);

    if (sanitizedValue === textInputValue) {
      event.target.value = sanitizedValue; // <---
    }
  };
```

**Comment by Coachonko** [comment]
Thank you for the suggestion, shouldn't Dark handle this situation internally though?

**Comment by atellmer** [comment]
> shouldn't Dark handle this situation internally though?

Dark does everything correctly here, because you call, for example, `setValue(0)`, then enter some letter, which is cut off, and you enter `setValue(0)` again. That is, the same value twice, but since the value is the same, the render does not start a second time.
Handling an input with a value transformation is a special case that is handled either by directly setting `target.value` or by re-rendering via `useUpdate()`.

**Comment by Coachonko** [comment]
Ok, if this is how Dark is supposed to handle it then I understand. I thought Dark would internally enforce input values like React,,, thank you for the information.

**Comment by atellmer** [comment]
Regarding React, I'm not sure that it will behave differently. This needs to be checked. But I remember when I was working with React I often had to interact with target.value also directly, solving similar problems.

**Comment by Coachonko** [comment]
I am moving some components from React to Dark and React does behave differently

**Comment by atellmer** [comment]
>  React to Dark and React does behave differently. 

You are right. I'll mark this ussue as bug.

**Comment by Coachonko** [comment]
This bugfix is exciting, can't wait!
